table vw_DichiarazioneKM

	measure 'KM Totali' =
			
			CALCULATE(
			    SUMX(
			        vw_DichiarazioneKM,
			        vw_DichiarazioneKM[KM_PERCORSI]
			    ),
			    vw_DichiarazioneKM[STATO] = "INSERITO",
			    NOT ISBLANK(vw_DichiarazioneKM[KM_PERCORSI])
			)
		formatString: 0

	measure 'KM Non Rendicontati' = ```
			
			SUMX(
			    FILTER(
			        vw_DichiarazioneKM,
			        vw_DichiarazioneKM[KM_SCARTO] <> 0
			    ),
			    ABS(vw_DichiarazioneKM[KM_SCARTO])
			)
			
			```
		formatString: 0

	measure 'N° Errori Contachilometri' =
			
			CALCULATE(
			    COUNTROWS(vw_DichiarazioneKM),
			    vw_DichiarazioneKM[KM_SCARTO] < 0
			)
		formatString: 0

	measure 'Tratte Aperte' =
			
			CALCULATE(
			    COUNTROWS(vw_DichiarazioneKM),
			    ISBLANK(vw_DichiarazioneKM[DATA_FINE]),
			    vw_DichiarazioneKM[STATO] = "INSERITO"
			)
		formatString: 0

	measure 'KM Medi per Tratta' =
			
			DIVIDE(
			    [KM Totali],
			    CALCULATE(
			        COUNTROWS(vw_DichiarazioneKM),
			        vw_DichiarazioneKM[STATO] = "INSERITO",
			        NOT ISBLANK(vw_DichiarazioneKM[KM_PERCORSI])
			    )
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KM Totali Matrice' =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            vw_DichiarazioneKM,
			            vw_DichiarazioneKM[STATO] = "INSERITO"
			            && NOT ISBLANK(vw_DichiarazioneKM[KM_PERCORSI])
			        ),
			        vw_DichiarazioneKM[KM_PERCORSI]
			    )
			)
		formatString: 0

	measure 'N° Tratte Matrice' =
			
			CALCULATE(
			    COUNTROWS(vw_DichiarazioneKM),
			    vw_DichiarazioneKM[STATO] = "INSERITO"
			)
		formatString: 0

	measure 'N° Utenti Attivi' = CALCULATE(DISTINCTCOUNT(vw_DichiarazioneKM[ID_USER]), vw_DichiarazioneKM[STATO] = "INSERITO")
		formatString: 0

	measure '% Scarto' =
			
			VAR KMTot = [KM Totali]
			VAR KMScarto = [KM Non Rendicontati]
			RETURN
			IF(
			    KMTot = 0 || ISBLANK(KMTot),
			    BLANK(),
			    DIVIDE(KMScarto, KMTot + KMScarto)
			)
		formatString: 0.0%;-0.0%;0.0%

	measure 'Ultima Dichiarazione' =
			
			CALCULATE(
			    MAX(vw_DichiarazioneKM[DATA_INIZIO]),
			    vw_DichiarazioneKM[STATO] = "INSERITO"
			)
		formatString: General Date

	measure 'KM Netti Totali' =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            vw_DichiarazioneKM,
			            vw_DichiarazioneKM[STATO] = "INSERITO"
			            && NOT ISBLANK(vw_DichiarazioneKM[KM_NETTI])
			        ),
			        vw_DichiarazioneKM[KM_NETTI]
			    )
			)
		formatString: 0

	measure 'Note Tratta' =
			IF(
			            ISINSCOPE(vw_DichiarazioneKM[Tratta]),
			            SELECTEDVALUE(vw_DichiarazioneKM[NOTE], "(note multiple)"),
			            BLANK()
			        )
		displayFolder: 📋 Dettaglio Tratta

	measure 'Data Fine Tratta' =
			IF(
			            ISINSCOPE(vw_DichiarazioneKM[Tratta]),
			            FORMAT(
			                SELECTEDVALUE(vw_DichiarazioneKM[DATA_FINE]),
			                "dd/MM/yyyy"
			            ),
			            BLANK()
			        )
		displayFolder: 📋 Dettaglio Tratta

	measure 'Ha Dati' = ```
			
			IF(
			    COUNTROWS(vw_DichiarazioneKM) > 0,
			    1,
			    BLANK()
			)
			
			```
		formatString: 0

	column ID
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column ID_USER
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: sum
		sourceColumn: ID_USER

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Cognome
		dataType: string
		summarizeBy: none
		sourceColumn: Cognome

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column CodiceSGA
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: CodiceSGA

		annotation SummarizationSetBy = Automatic

	column TARGA
		dataType: string
		summarizeBy: none
		sourceColumn: TARGA

		annotation SummarizationSetBy = Automatic

	column DATA_INIZIO
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: DATA_INIZIO

		variation Variazione
			isDefault
			relationship: 2b094b0f-d47a-4ff0-8ad5-4bfc6044e897
			defaultHierarchy: LocalDateTable_5f463ee9-9e83-46a1-a874-c3f2357fae2d.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column DATA_FINE
		dataType: dateTime
		formatString: General Date
		displayFolder: Dettaglio Tratta
		summarizeBy: none
		sourceColumn: DATA_FINE

		variation Variazione
			isDefault
			relationship: aef4b689-9448-4306-91cf-f349f4a1656a
			defaultHierarchy: LocalDateTable_ef80951f-2035-4adf-921c-6be6cef02011.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column PUNTO_INIZIO
		dataType: string
		displayFolder: Dettaglio Tratta
		summarizeBy: none
		sourceColumn: PUNTO_INIZIO

		annotation SummarizationSetBy = Automatic

	column PUNTO_FINE
		dataType: string
		displayFolder: Dettaglio Tratta
		summarizeBy: none
		sourceColumn: PUNTO_FINE

		annotation SummarizationSetBy = Automatic

	column KM_INIZIO
		dataType: int64
		formatString: 0
		displayFolder: KM
		summarizeBy: sum
		sourceColumn: KM_INIZIO

		annotation SummarizationSetBy = Automatic

	column KM_FINE
		dataType: int64
		formatString: 0
		displayFolder: KM
		summarizeBy: sum
		sourceColumn: KM_FINE

		annotation SummarizationSetBy = Automatic

	column KM_PERCORSI
		dataType: int64
		formatString: 0
		displayFolder: KM
		summarizeBy: sum
		sourceColumn: KM_PERCORSI

		annotation SummarizationSetBy = Automatic

	column KM_SCARTO
		dataType: int64
		formatString: 0
		displayFolder: KM
		summarizeBy: sum
		sourceColumn: KM_SCARTO

		annotation SummarizationSetBy = Automatic

	column KM_NETTI
		dataType: int64
		formatString: 0
		displayFolder: KM
		summarizeBy: sum
		sourceColumn: KM_NETTI

		annotation SummarizationSetBy = Automatic

	column NOTE
		dataType: string
		displayFolder: Dettaglio Tratta
		summarizeBy: none
		sourceColumn: NOTE

		annotation SummarizationSetBy = Automatic

	column STATO
		dataType: string
		summarizeBy: none
		sourceColumn: STATO

		annotation SummarizationSetBy = Automatic

	column DATA_INSERT
		dataType: dateTime
		formatString: General Date
		displayFolder: Dettaglio Tratta
		summarizeBy: none
		sourceColumn: DATA_INSERT

		variation Variazione
			isDefault
			relationship: e8e8a6f9-05b1-42ca-9635-6c08d85f7034
			defaultHierarchy: LocalDateTable_b9243c96-6d6a-4762-97e4-e1fdf355f828.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column DATA_UPDATE
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: DATA_UPDATE

		variation Variazione
			isDefault
			relationship: 3c133064-64d2-4897-971f-09555e5a01ee
			defaultHierarchy: LocalDateTable_24902f4c-331c-4267-925a-3572b25dad05.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column ANNO
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Gerarchia Temporale
		summarizeBy: sum
		sourceColumn: ANNO

		annotation SummarizationSetBy = Automatic

	column MESE
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Gerarchia Temporale
		summarizeBy: sum
		sourceColumn: MESE

		annotation SummarizationSetBy = Automatic

	column NOME_MESE
		dataType: string
		isHidden
		displayFolder: Gerarchia Temporale
		summarizeBy: none
		sourceColumn: NOME_MESE

		annotation SummarizationSetBy = Automatic

	column NomeCompleto = ```
			
			IF(
			    ISBLANK(vw_DichiarazioneKM[Nome]) || ISBLANK(vw_DichiarazioneKM[Cognome]),
			    COALESCE(vw_DichiarazioneKM[Nome], vw_DichiarazioneKM[Cognome], "Utente sconosciuto"),
			    vw_DichiarazioneKM[Nome] & " " & vw_DichiarazioneKM[Cognome]
			)
			
			```
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MeseAnno = ```
			
			FORMAT(vw_DichiarazioneKM[DATA_INIZIO], "MMM YYYY")
			
			```
		displayFolder: Gerarchia Temporale
		summarizeBy: none
		sortByColumn: SortMeseAnno

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column SortMeseAnno = ```
			
			vw_DichiarazioneKM[ANNO] * 100 + vw_DichiarazioneKM[MESE]
			
			```
		isHidden
		formatString: 0
		displayFolder: Gerarchia Temporale
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Giorno = DAY(vw_DichiarazioneKM[DATA_INIZIO])
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Gerarchia Temporale
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column GiornoData = FORMAT(vw_DichiarazioneKM[DATA_INIZIO], "ddd dd/MM")
		dataType: string
		displayFolder: Gerarchia Temporale
		summarizeBy: none
		sortByColumn: SortGiornoData

		annotation SummarizationSetBy = Automatic

	column SortGiornoData =
			vw_DichiarazioneKM[ANNO] * 10000
			        + vw_DichiarazioneKM[MESE] * 100
			        + DAY(vw_DichiarazioneKM[DATA_INIZIO])
		dataType: int64
		isHidden
		displayFolder: Gerarchia Temporale
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Tratta = ```
			
			VAR PuntoInizio = vw_DichiarazioneKM[PUNTO_INIZIO]
			VAR PuntoFine   = vw_DichiarazioneKM[PUNTO_FINE]
			VAR Stato       = vw_DichiarazioneKM[STATO]
			RETURN
			    SWITCH(
			        TRUE(),
			        NOT ISBLANK(PuntoFine),
			            PuntoInizio & " → " & PuntoFine,
			        ISBLANK(PuntoFine) && Stato = "INSERITO",
			            PuntoInizio & " → ⏳ in corso",
			        ISBLANK(PuntoFine) && Stato = "ANNULLATO",
			            PuntoInizio & " → ❌ annullata senza fine",
			        PuntoInizio & " → (sconosciuta)"
			    )
			
			```
		dataType: string
		displayFolder: Dettaglio Tratta
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Gerarchia Data'
		displayFolder: Gerarchia Temporale

		level Anno
			column: ANNO

		level Mese
			column: MeseAnno

		level Giorno
			column: GiornoData

	partition vw_DichiarazioneKM = m
		mode: import
		source =
				let
				    Origine = Sql.Database("sqltorello1.8e5e8f166c55.database.windows.net", "sgam_analisi"),
				    dbo_vw_DichiarazioneKM = Origine{[Schema="dbo",Item="vw_DichiarazioneKM"]}[Data]
				in
				    dbo_vw_DichiarazioneKM

	annotation PBI_ResultType = Table

